version: '3' #version

services:
  db:
    image: mysql:5.7 #imagename:version
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USERNAME: wordpressuser
      MYSQL_PASSWORD: wordpressuser

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8092:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306

volumes:
  db_data: